apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-2
      # auth:
      #   jwt:
      #     serviceAccountRef:
      #       name: external-secrets
      #       namespace: ext-external-secrets